--- # adds kubernetes repo and installs/enables kubelet
- hosts: cluster
  become: yes
  tasks:
  - name: Disable SELinux
    selinux: state=disabled

  - name: Configure sysctl for ipv4
    sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      sysctl_set: yes
      state: present
      reload: yes

  - name: Configure sysctl for ipv6
    sysctl:
      name: net.bridge.bridge-nf-call-ip6tables
      value: 1
      sysctl_set: yes
      state: present
      reload: yes

  - name: Add Kubernetes repository
    yum_repository:
      name: Kubernetes
      description: k8s repo
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      gpgcheck: yes

  - name: Install packages
    yum: name={{item}} state=present
    with_items:
    - docker
    - kubelet
    - kubeadm
    - kubectl

  - name: Start and enable services
    service: name={{item}} state=started enabled=yes
    with_items:
    - docker
    - kubelet
